// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt07ykwc4L5FpHLhUaiVgVBHKCkjpDVdI',
    appId: '1:17369690319:web:f76aaa41419c010e1a47ba',
    messagingSenderId: '17369690319',
    projectId: 'taskflow-d054c',
    authDomain: 'taskflow-d054c.firebaseapp.com',
    storageBucket: 'taskflow-d054c.firebasestorage.app',
    measurementId: 'G-K3YX9R3J3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtKIKWdKeSj1QHQ74wR7JYD9QGxmaeaKc',
    appId: '1:17369690319:android:f4f91f9c60e7aa021a47ba',
    messagingSenderId: '17369690319',
    projectId: 'taskflow-d054c',
    storageBucket: 'taskflow-d054c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq27ai6i4ogJqEFUVrir4MeFCPYLDI5l4',
    appId: '1:17369690319:ios:e6d908e7cf049bb41a47ba',
    messagingSenderId: '17369690319',
    projectId: 'taskflow-d054c',
    storageBucket: 'taskflow-d054c.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq27ai6i4ogJqEFUVrir4MeFCPYLDI5l4',
    appId: '1:17369690319:ios:e6d908e7cf049bb41a47ba',
    messagingSenderId: '17369690319',
    projectId: 'taskflow-d054c',
    storageBucket: 'taskflow-d054c.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );
}
